[package]
name = "rsblocks"
version = "0.1.1"
authors = ["mustafa salih <mustafasalih1991@gmail.com>"]
edition = "2018"
readme = "README.md"
license = "MIT"
repository = "https://github.com/MustafaSalih1993/rsblocks"
description = "This is a minimal status bar for dwm window manager for linux"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
yaml-rust = "0.4"